FROM kbase/sdkbase2:python
MAINTAINER KBase Developer
# -----------------------------------------
# In this section, you can install any system dependencies required
# to run your App.  For instance, you could place an apt-get update or
# install line here, a git checkout to download code, or run any other
# installation scripts.

RUN apt-get update
RUN apt-get install -y python-pip python-pandas python-openopt
RUN apt-get install -y bowtie samtools bedtools emboss python3-pip python3-pandas wget zlib1g-dev emacs bc gawk
RUN wget https://github.com/bedops/bedops/releases/download/v2.4.35/bedops_linux_x86_64-v2.4.35.tar.bz2 && tar jxf bedops_linux_x86_64-v2.4.35.tar.bz2 && cp bin/* /usr/local/bin/
RUN pip3 install --upgrade pip
RUN pip3 install openopt
RUN pip3 install biopython
RUN pip3 install pandas
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install FuncDesigner
RUN pip3 install DerApproximator
RUN pip install openopt
RUN pip2 install pandas
RUN pip2 install numpy
RUN pip2 install scipy
RUN git clone https://github.com/lh3/bwa.git && cd bwa && make && cp bwa /usr/local/bin/
RUN conda install pandas --yes
RUN conda install scipy --yes
RUN git clone -b py3 https://github.com/jmchandonia/meta_decoder.git

# -----------------------------------------

COPY ./ /kb/module
RUN mkdir -p /kb/module/work
RUN chmod -R a+rw /kb/module

WORKDIR /kb/module

RUN make all

ENTRYPOINT [ "./scripts/entrypoint.sh" ]

CMD [ ]
